ALL TESTS:

python manage.py test hotel_app   


--

PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app     
Found 48 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 22:23:08.133246) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 22:23:08.150193) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 22:23:08.154298) while time zone support is active.
  warnings.warn(
.C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 22:23:08.182887) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 22:23:08.189258) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 22:23:08.195347) while time zone support is active.
  warnings.warn(
.C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 22:23:08.237157) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 22:23:08.241891) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 22:23:08.246194) while time zone support is active.
  warnings.warn(
.C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 22:23:08.282584) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 22:23:08.287518) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 22:23:08.293257) while time zone support is active.
  warnings.warn(
.C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 22:23:08.320205) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 22:23:08.325077) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 22:23:08.329017) while time zone support is active.
  warnings.warn(
.C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 22:23:08.364955) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 22:23:08.371303) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 22:23:08.375585) while time zone support is active.
  warnings.warn(
.C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 22:23:08.401431) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 22:23:08.406181) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 22:23:08.411125) while time zone support is active.
  warnings.warn(
..INFO:hotel_app.views:Room list view accessed by user: staffuser
INFO:hotel_app.views:Retrieved 0 rooms after filtering
.INFO:hotel_app.forms:Validating guest form data for John Smith
.INFO:hotel_app.forms:Validating guest form data for John Smith
..INFO:hotel_app.models:Room __str__ called: 101
.INFO:hotel_app.models:RoomType __str__ called: Standard Room
....INFO:hotel_app.views:Room list view accessed by user: testuser
INFO:hotel_app.views:Retrieved 1 rooms after filtering
..INFO:hotel_app.models:Guest display_name property called: Mr J. Smith
.INFO:hotel_app.models:Guest __str__ called: ID:1: Full name:Mr John Smith
...C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-23 22:23:19.301566) while time zone support is active.
  warnings.warn(
INFO:hotel_app.models:Reservation end_date property called: 2025-02-25
.C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-23 22:23:19.308604) while time zone support is active.
  warnings.warn(
.C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-23 22:23:19.314193) while time zone support is active.
  warnings.warn(
.C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-23 22:23:19.320649) while time zone support is active.
  warnings.warn(
.C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-23 22:23:19.327421) while time zone support is active.
  warnings.warn(
INFO:hotel_app.models:Reservation __str__ called: Reservation 1 - RE
..INFO:hotel_app.models:Room __str__ called: 101
...INFO:hotel_app.models:RoomType __str__ called: Standard Room
.WARNING:hotel_app.forms:Room type form validation failed
INFO:hotel_app.forms:Form errors: <ul class="errorlist"><li>room_type_code<ul class="errorlist"><li>This field is required.</li></ul></li><li>room_type_name<ul class="errorlist"><li>This field is required.</li></ul></li><li>price<ul class="errorlist"><li>Enter a number.</li></ul></li><li>maximum_guests<ul class="errorlist"><li>Enter a whole number.</li></ul></li></ul>     
.WARNING:hotel_app.forms:Room type form validation failed
INFO:hotel_app.forms:Form errors: <ul class="errorlist"><li>room_type_code<ul class="errorlist"><li>This field is required.</li></ul></li><li>room_type_name<ul class="errorlist"><li>This field is required.</li></ul></li><li>price<ul class="errorlist"><li>This field is required.</li></ul></li><li>maximum_guests<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
.INFO:hotel_app.forms:Validating room type form - Code: DOD, Name: Double Deluxe, Price: 125.0
.........INFO:hotel_app.views:Guest deletion initiated for guest_id: 1 by user: test_user
INFO:hotel_app.models:Guest display_name property called: Mr J. Smith
INFO:hotel_app.views:Found guest to delete: Mr J. Smith
INFO:hotel_app.models:Guest display_name property called: Mr J. Smith
INFO:hotel_app.views:Displaying delete confirmation page for guest: Mr J. Smith
INFO:hotel_app.views:Guest deletion initiated for guest_id: 1 by user: test_user
INFO:hotel_app.models:Guest display_name property called: Mr J. Smith
INFO:hotel_app.views:Found guest to delete: Mr J. Smith
INFO:hotel_app.models:Guest display_name property called: Mr J. Smith
INFO:hotel_app.views:Successfully deleted guest - ID: 1, Name: Mr J. Smith
....
----------------------------------------------------------------------
Ran 48 tests in 17.812s

OK
Destroying test database for alias 'default'...

------------------

filters_test.py:

python manage.py test hotel_app.filters_test

--

when it passed:

PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.filters_test
Found 6 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
......
----------------------------------------------------------------------
Ran 6 tests in 0.014s

OK
Destroying test database for alias 'default'...



--

when it failed:

PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.filters_test
Found 6 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
EEE...
======================================================================
ERROR: test_filter_guests_by_last_name_case_insensitive (hotel_app.filters_test.TestGuestFilter.test_filter_guests_by_last_name_case_insensitive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 25, in test_filter_guests_by_last_name_case_insensitive
    filter_instance = GuestFilter({'last_name': 'smith'}, queryset=Guest.objects.all())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 196, in __init__
    model = queryset.model
            ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'model'

======================================================================
ERROR: test_filter_guests_by_postcode_partial_match (hotel_app.filters_test.TestGuestFilter.test_filter_guests_by_postcode_partial_match)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 33, in test_filter_guests_by_postcode_partial_match
    filter_instance = GuestFilter({'postcode': '123'}, queryset=Guest.objects.all())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 196, in __init__
    model = queryset.model
            ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'model'

======================================================================
ERROR: test_guest_filter_correctly_filters_by_last_name_and_postcode (hotel_app.filters_test.TestGuestFilter.test_guest_filter_correctly_filters_by_last_name_and_postcode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 46, in test_guest_filter_correctly_filters_by_last_name_and_postcode
    filter_instance = GuestFilter({'last_name': 'smith', 'postcode': '123'}, queryset=Guest.objects.all())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 196, in __init__
    model = queryset.model
            ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'model'

----------------------------------------------------------------------
Ran 6 tests in 0.043s

FAILED (errors=3)
Destroying test database for alias 'default'...
PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.filters_test
Found 6 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
FFF...
======================================================================
FAIL: test_filter_guests_by_last_name_case_insensitive (hotel_app.filters_test.TestGuestFilter.test_filter_guests_by_last_name_case_insensitive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 34, in test_filter_guests_by_last_name_case_insensitive
    filtered_guests = filter_instance.qs
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 250, in qs
    qs = self.filter_queryset(qs)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 234, in filter_queryset
    assert isinstance(
           ^^^^^^^^^^^
AssertionError: Expected 'GuestFilter.last_name' to return a QuerySet, but got a MagicMock instead.

======================================================================
FAIL: test_filter_guests_by_postcode_partial_match (hotel_app.filters_test.TestGuestFilter.test_filter_guests_by_postcode_partial_match)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 42, in test_filter_guests_by_postcode_partial_match
    filtered_guests = filter_instance.qs
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 250, in qs
    qs = self.filter_queryset(qs)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 234, in filter_queryset
    assert isinstance(
           ^^^^^^^^^^^
AssertionError: Expected 'GuestFilter.last_name' to return a QuerySet, but got a MagicMock instead.

======================================================================
FAIL: test_guest_filter_correctly_filters_by_last_name_and_postcode (hotel_app.filters_test.TestGuestFilter.test_guest_filter_correctly_filters_by_last_name_and_postcode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 55, in test_guest_filter_correctly_filters_by_last_name_and_postcode
    filtered_guests = filter_instance.qs
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 250, in qs
    qs = self.filter_queryset(qs)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 234, in filter_queryset
    assert isinstance(
           ^^^^^^^^^^^
AssertionError: Expected 'GuestFilter.last_name' to return a QuerySet, but got a MagicMock instead.

----------------------------------------------------------------------
Ran 6 tests in 0.019s

FAILED (failures=3)
Destroying test database for alias 'default'...
PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.filters_test
Found 6 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
FFF...
======================================================================
FAIL: test_filter_guests_by_last_name_case_insensitive (hotel_app.filters_test.TestGuestFilter.test_filter_guests_by_last_name_case_insensitive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 51, in test_filter_guests_by_last_name_case_insensitive
    filtered_guests = filter_instance.qs
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 250, in qs
    qs = self.filter_queryset(qs)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 234, in filter_queryset
    assert isinstance(
           ^^^^^^^^^^^
AssertionError: Expected 'GuestFilter.last_name' to return a QuerySet, but got a MagicMock instead.

======================================================================
FAIL: test_filter_guests_by_postcode_partial_match (hotel_app.filters_test.TestGuestFilter.test_filter_guests_by_postcode_partial_match)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 59, in test_filter_guests_by_postcode_partial_match
    filtered_guests = filter_instance.qs
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 250, in qs
    qs = self.filter_queryset(qs)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 234, in filter_queryset
    assert isinstance(
           ^^^^^^^^^^^
AssertionError: Expected 'GuestFilter.last_name' to return a QuerySet, but got a MagicMock instead.

======================================================================
FAIL: test_guest_filter_correctly_filters_by_last_name_and_postcode (hotel_app.filters_test.TestGuestFilter.test_guest_filter_correctly_filters_by_last_name_and_postcode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 72, in test_guest_filter_correctly_filters_by_last_name_and_postcode
    filtered_guests = filter_instance.qs
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 250, in qs
    qs = self.filter_queryset(qs)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django_filters\filterset.py", line 234, in filter_queryset
    assert isinstance(
           ^^^^^^^^^^^
AssertionError: Expected 'GuestFilter.last_name' to return a QuerySet, but got a MagicMock instead.

----------------------------------------------------------------------
Ran 6 tests in 0.016s

FAILED (failures=3)
Destroying test database for alias 'default'...
PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.filters_test
Found 6 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..F...
======================================================================
FAIL: test_guest_filter_correctly_filters_by_last_name_and_postcode (hotel_app.filters_test.TestGuestFilter.test_guest_filter_correctly_filters_by_last_name_and_postcode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 64, in test_guest_filter_correctly_filters_by_last_name_and_postcode
    self.assertEqual(len(filtered_guests), 1)
AssertionError: 2 != 1

----------------------------------------------------------------------
Ran 6 tests in 0.019s

FAILED (failures=1)
Destroying test database for alias 'default'...
PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.filters_test
Found 6 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.F....
======================================================================
FAIL: test_filter_guests_by_postcode_partial_match (hotel_app.filters_test.TestGuestFilter.test_filter_guests_by_postcode_partial_match)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 50, in test_filter_guests_by_postcode_partial_match
    self.assertEqual(len(filtered_guests), 2)
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 6 tests in 0.020s

FAILED (failures=1)
Destroying test database for alias 'default'...






PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2> python manage.py test hotel_app.filters_test
>> 
C:\Python311\python.exe: can't open file 'C:\\Users\\aidan_1k98io6\\OneDrive\\Documents\\Assignment\\Software Engineering\\hotel_project2\\manage.py': [Errno 2] No such file or directory
PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2> cd hotel_project
PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.filters_test
>>
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\manage.py", line 22, in <module>
    main()
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\aidan_1k98io6\AppData\Roaming\Python\Python311\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\aidan_1k98io6\AppData\Roaming\Python\Python311\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "C:\Users\aidan_1k98io6\AppData\Roaming\Python\Python311\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\aidan_1k98io6\AppData\Roaming\Python\Python311\site-packages\django\apps\registry.py", line 91, in populate 
    app_config = AppConfig.create(entry)
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\AppData\Roaming\Python\Python311\site-packages\django\apps\config.py", line 193, in create    
    import_module(entry)
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'django_filters'
PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> pipenv shell
Launching subshell in virtual environment...
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2> python manage.py test hotel_app.filters_test
>>
C:\Users\aidan_1k98io6\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'C:\\Users\\aidan_1k98io6\\OneDrive\\Documents\\Assignment\\Software Engineering\\hotel_project2\\manage.py': [Errno 2] No such file or directory
PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2> cd hotel_project
PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.filters_test
>>
Found 6 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.INFO:hotel_app.filters:Filtering guests by postcode: 123
WARNING:hotel_app.filters:Invalid postcode format: 123
FINFO:hotel_app.filters:Filtering guests by postcode: 123
WARNING:hotel_app.filters:Invalid postcode format: 123
F...
======================================================================
FAIL: test_filter_guests_by_postcode_partial_match (hotel_app.filters_test.TestGuestFilter.test_filter_guests_by_postcode_partial_match)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 50, in test_filter_guests_by_postcode_partial_match
    self.assertEqual(len(filtered_guests), 2)
AssertionError: 0 != 2

======================================================================
FAIL: test_guest_filter_correctly_filters_by_last_name_and_postcode (hotel_app.filters_test.TestGuestFilter.test_guest_filter_correctly_filters_by_last_name_and_postcode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 64, in test_guest_filter_correctly_filters_by_last_name_and_postcode
    self.assertEqual(len(filtered_guests), 1)
AssertionError: 0 != 1

Ran 6 tests in 0.027s

FAILED (failures=2)
Destroying test database for alias 'default'...
PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project>
                                                                                                           python manage.py test hotel_app.filters_test
>>
Found 6 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.INFO:hotel_app.filters:Filtering guests by postcode: SW1A
WARNING:hotel_app.filters:Invalid postcode format: SW1A
FINFO:hotel_app.filters:Filtering guests by postcode: SW1A 2AA
INFO:hotel_app.filters:Exact match for postcode as last_name is also provided: SW1A 2AA
....
======================================================================
FAIL: test_filter_guests_by_postcode_partial_match (hotel_app.filters_test.TestGuestFilter.test_filter_guests_by_postcode_partial_match)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 50, in test_filter_guests_by_postcode_partial_match
    self.assertEqual(len(filtered_guests), 2)
AssertionError: 0 != 2

----------------------------------------------------------------------
Ran 6 tests in 0.020s

FAILED (failures=1)
Destroying test database for alias 'default'...
PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.filters_test
Found 6 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.INFO:hotel_app.filters:Filtering guests by postcode: SW1A 1AA
INFO:hotel_app.filters:Partial match for postcode: SW1A 1AA
FINFO:hotel_app.filters:Filtering guests by postcode: SW1A 2AA
INFO:hotel_app.filters:Exact match for postcode as last_name is also provided: SW1A 2AA
....
======================================================================
FAIL: test_filter_guests_by_postcode_partial_match (hotel_app.filters_test.TestGuestFilter.test_filter_guests_by_postcode_partial_match)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\filters_test.py", line 50, in test_filter_guests_by_postcode_partial_match
    self.assertEqual(len(filtered_guests), 2)
AssertionError: 1 != 2

----------------------------------------------------------------------
Ran 6 tests in 0.022s

FAILED (failures=1)
Destroying test database for alias 'default'...





-------------------------------------------------------------

tests.py:

python manage.py test hotel_app.tests

PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project>
                                                                                                           python manage.py test hotel_app -v 2
Found 15 test(s).
Creating test database for alias 'default' ('file:memorydb_default?mode=memory&cache=shared')...
Operations to perform:
  Synchronize unmigrated apps: crispy_bootstrap5, crispy_forms, django_filters, messages, staticfiles, widget_tweaks
  Apply all migrations: admin, auth, contenttypes, hotel_app, sessions
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying hotel_app.0001_initial... OK
  Applying hotel_app.0002_alter_reservation_guest_and_more... OK
  Applying hotel_app.0003_alter_guest_address_line1_alter_guest_address_line2_and_more... OK
  Applying hotel_app.0004_alter_guest_phone_number_alter_guest_postcode_and_more... OK
  Applying sessions.0001_initial... OK
System check identified no issues (0 silenced).
test_guest_creation (hotel_app.tests.GuestModelTest.test_guest_creation) ... ok
test_guest_display_name (hotel_app.tests.GuestModelTest.test_guest_display_name) ... INFO:hotel_app.models:Guest display_name property called: Mr J. Smith
ok
test_guest_str_method (hotel_app.tests.GuestModelTest.test_guest_str_method) ... INFO:hotel_app.models:Guest __str__ called: ID:1: Full name:Mr John Smith
ok
test_invalid_phone_number (hotel_app.tests.GuestModelTest.test_invalid_phone_number) ... ok
test_invalid_title (hotel_app.tests.GuestModelTest.test_invalid_title) ... ok
test_end_date_calculation (hotel_app.tests.ReservationModelTest.test_end_date_calculation) ... C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-23 16:56:39.560151) while time zone support is active.       
  warnings.warn(
INFO:hotel_app.models:Reservation end_date property called: 2025-02-25
ok
test_invalid_guest_count (hotel_app.tests.ReservationModelTest.test_invalid_guest_count) ... C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-23 16:56:39.650477) while time zone support is active.
  warnings.warn(
ok
test_invalid_payment_amount (hotel_app.tests.ReservationModelTest.test_invalid_payment_amount) ... C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-23 16:56:39.654965) while time zone support is active.   
  warnings.warn(
ok
test_reservation_creation (hotel_app.tests.ReservationModelTest.test_reservation_creation) ... C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-23 16:56:39.662330) while time zone support is active.       
  warnings.warn(
ok
test_reservation_str_method (hotel_app.tests.ReservationModelTest.test_reservation_str_method) ... C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-23 16:56:39.666072) while time zone support is active.   
  warnings.warn(
INFO:hotel_app.models:Reservation __str__ called: Reservation 1 - RE
ok
test_room_creation (hotel_app.tests.RoomModelTest.test_room_creation) ... ok
test_room_str_method (hotel_app.tests.RoomModelTest.test_room_str_method) ... INFO:hotel_app.models:Room __str__ called: 101 
ok
test_invalid_room_type_code (hotel_app.tests.RoomTypeModelTest.test_invalid_room_type_code) ... ok
test_room_type_creation (hotel_app.tests.RoomTypeModelTest.test_room_type_creation) ... ok
test_room_type_str_method (hotel_app.tests.RoomTypeModelTest.test_room_type_str_method) ... INFO:hotel_app.models:RoomType __str__ called: Standard Room
ok

----------------------------------------------------------------------
Ran 15 tests in 0.152s

OK



-----------------------


test_unit.py:

 python manage.py test hotel_app.test_unit

PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.test_unit
Found 11 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.INFO:hotel_app.views:Room list view accessed by user: staffuser
INFO:hotel_app.views:Retrieved 0 rooms after filtering
.INFO:hotel_app.forms:Validating guest form data for John Smith
.INFO:hotel_app.forms:Validating guest form data for John Smith
..INFO:hotel_app.models:Room __str__ called: 101
.INFO:hotel_app.models:RoomType __str__ called: Standard Room
....INFO:hotel_app.views:Room list view accessed by user: testuser
INFO:hotel_app.views:Retrieved 1 rooms after filtering
.
----------------------------------------------------------------------
Ran 11 tests in 11.938s

OK
Destroying test database for alias 'default'...


PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.test_unit      
Found 11 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.FINFO:hotel_app.forms:Validating guest form data for John Smith
.INFO:hotel_app.forms:Validating guest form data for John Smith
..INFO:hotel_app.models:Room __str__ called: 101
.INFO:hotel_app.models:RoomType __str__ called: Standard Room
....F
======================================================================
FAIL: test_staff_permissions (hotel_app.test_unit.AuthenticationTestCase.test_staff_permissions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\test_unit.py", line 177, in test_staff_permissions
    self.assertEqual(response.status_code, 200)  # Should have access
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 302 != 200

======================================================================
FAIL: test_room_list_view (hotel_app.test_unit.ViewsTestCase.test_room_list_view)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\test_unit.py", line 83, in test_room_list_view
    self.assertEqual(response.status_code, 200)
AssertionError: 302 != 200

----------------------------------------------------------------------
Ran 11 tests in 13.567s

FAILED (failures=2)
Destroying test database for alias 'default'...


PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.tests.test_unit
Found 8 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
INFO:hotel_app.forms:Validating guest form data for John Smith
.INFO:hotel_app.forms:Validating guest form data for John Smith
..INFO:hotel_app.models:Room __str__ called: 101
.INFO:hotel_app.models:RoomType __str__ called: Standard Room
.EFE
======================================================================
ERROR: test_guest_list_view (hotel_app.tests.test_unit.ViewsTestCase.test_guest_list_view)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\tests\test_unit.py", line 55, in test_guest_list_view
    response = self.client.get(reverse('guest-list'))
                               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'guest-list' not found. 'guest-list' is not a valid view function or pattern name.

======================================================================
ERROR: test_room_list_view (hotel_app.tests.test_unit.ViewsTestCase.test_room_list_view)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\tests\test_unit.py", line 62, in test_room_list_view
    response = self.client.get(reverse('room-list'))
                               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'room-list' not found. 'room-list' is not a valid view function or pattern name.

======================================================================
FAIL: test_home_view (hotel_app.tests.test_unit.ViewsTestCase.test_home_view)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\tests\test_unit.py", line 50, in test_home_view
    self.assertEqual(response.status_code, 200)
AssertionError: 302 != 200

----------------------------------------------------------------------
Ran 8 tests in 6.593s

FAILED (failures=1, errors=2)
Destroying test database for alias 'default'...





------------------------------------

test_data.py:

python manage.py test hotel_app.test_data

Ran 7 tests in 0.194s

OK
Destroying test database for alias 'default'...

PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.test_data
Found 7 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 18:02:38.982092) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 18:02:38.996429) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 18:02:38.997680) while time zone support is active.
  warnings.warn(
.C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 18:02:39.021324) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 18:02:39.023173) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 18:02:39.024395) while time zone support is active.
  warnings.warn(
FC:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 18:02:39.053341) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 18:02:39.055639) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 18:02:39.057545) while time zone support is active.
  warnings.warn(
.C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 18:02:39.086846) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 18:02:39.088774) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 18:02:39.090011) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-23 18:02:39.091681) while time zone support is active.
  warnings.warn(
FC:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 18:02:39.120431) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 18:02:39.122326) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 18:02:39.125169) while time zone support is active.
  warnings.warn(
EC:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 18:02:39.269842) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 18:02:39.272459) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 18:02:39.274376) while time zone support is active.
  warnings.warn(
FC:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-16 18:02:39.320271) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-02-09 18:02:39.322510) while time zone support is active.
  warnings.warn(
C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\fields\__init__.py:1665: RuntimeWarning: DateTimeField Reservation.reservation_date_time received a naive datetime (2025-01-24 18:02:39.325241) while time zone support is active.
  warnings.warn(
.
======================================================================
ERROR: test_room_availability (hotel_app.test_data.TestDataGenerator.test_room_availability)
Test room availability checking.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\sql\query.py", line 1517, in build_filter
    join_info = self.setup_joins(
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\sql\query.py", line 1863, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\sql\query.py", line 1792, in names_to_path
    raise MultiJoin(pos + 1, names_with_path)
django.db.models.sql.datastructures.MultiJoin: (1, [('reservations', [PathInfo(from_opts=<Options for Room>, to_opts=<Options for Reservation>, target_fields=(<django.db.models.fields.AutoField: reservation_id>,), join_field=<ManyToOneRel: hotel_app.reservation>, m2m=True, direct=False, filtered_relation=None)])])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\test_data.py", line 343, in test_room_availability
    ).exclude(
      ^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\query.py", line 1484, in exclude
    return self._filter_or_exclude(True, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\query.py", line 1499, in _filter_or_exclude_inplace
    self._query.add_q(~Q(*args, **kwargs))
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\sql\query.py", line 1534, in build_filter
    return self.split_exclude(filter_expr, can_reuse, e.names_with_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\sql\query.py", line 2058, in split_exclude
    query.add_filter(filter_lhs, filter_rhs)
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\sql\query.py", line 1593, in add_filter
    self.add_q(Q((filter_lhs, filter_rhs)))
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\sql\query.py", line 1372, in build_lookup
    lhs = self.try_transform(lhs, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\sql\query.py", line 1423, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'end_date' for ManyToOneRel or join on the field not permitted.        

======================================================================
FAIL: test_guest_validation (hotel_app.test_data.TestDataGenerator.test_guest_validation)
Test guest data validation.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\test_data.py", line 352, in test_guest_validation
    with self.assertRaises(ValidationError):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ValidationError not raised

======================================================================
FAIL: test_reservation_validation (hotel_app.test_data.TestDataGenerator.test_reservation_validation)
Test reservation validation rules.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\test_data.py", line 369, in test_reservation_validation
    with self.assertRaises(ValidationError):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: ValidationError not raised

======================================================================
FAIL: test_room_creation (hotel_app.test_data.TestDataGenerator.test_room_creation)
Test that all rooms were created correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\test_data.py", line 316, in test_room_creation
    self.assertEqual(Room.objects.count(), 18)
AssertionError: 19 != 18

----------------------------------------------------------------------
Ran 7 tests in 0.381s

FAILED (failures=3, errors=1)
Destroying test database for alias 'default'...








-------------------------------------------


test_integration.py:

python manage.py test hotel_app.test_integration



INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
INFO:hotel_app.views:Found guest for reservation: Dr M. Taylor
INFO:hotel_app.views:Retrieved room number from session: 301
INFO:hotel_app.views:Found room for reservation: Room 301 (Luxury Suite)
INFO:hotel_app.views:Reservation details:
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
INFO:hotel_app.views: - Guest: Dr M. Taylor (ID: 1)
INFO:hotel_app.views: - Room: 301 (Luxury Suite)
INFO:hotel_app.views: - Check-in: 2025-03-16
INFO:hotel_app.views: - Length of stay: 3 nights
INFO:hotel_app.views: - Price per night: £300.00
INFO:hotel_app.views: - Total price: £900.00
INFO:hotel_app.views:Processing reservation form submission
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
WARNING:hotel_app.views:Reservation form validation failed
INFO:hotel_app.views:Form errors: <ul class="errorlist"><li>amount_paid<ul class="errorlist"><li>Payment amount cannot exceed the total price of 900.00</li></ul></li><li>__all__<ul class="errorlist nonfield"><li>Payment amount is required</li></ul></li></ul>
INFO:hotel_app.views:Reservation creation initiated for guest_id: 1 by user: testuser
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
INFO:hotel_app.views:Found guest for reservation: Dr M. Taylor
INFO:hotel_app.views:Retrieved room number from session: 301
INFO:hotel_app.views:Found room for reservation: Room 301 (Luxury Suite)
INFO:hotel_app.views:Reservation details:
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
INFO:hotel_app.views: - Guest: Dr M. Taylor (ID: 1)
INFO:hotel_app.views: - Room: 301 (Luxury Suite)
INFO:hotel_app.views: - Check-in: 2025-03-16
INFO:hotel_app.views: - Length of stay: 3 nights
INFO:hotel_app.views: - Price per night: £300.00
INFO:hotel_app.views: - Total price: £900.00
INFO:hotel_app.views:Processing reservation form submission
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
INFO:hotel_app.views:Reservation form validation successful
INFO:hotel_app.forms:Reservation Form save
INFO:hotel_app.forms: - reservation_id: None
INFO:hotel_app.forms: - guest: None
INFO:hotel_app.forms: - room_number: None
INFO:hotel_app.forms: - reservation_date_time: datetime.datetime(2025, 2, 23, 23, 57, 27, 943410, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
INFO:hotel_app.forms: - price: Decimal('900.00')
INFO:hotel_app.forms: - amount_paid: Decimal('450.00')
INFO:hotel_app.forms: - number_of_guests: 2
INFO:hotel_app.forms: - start_of_stay: datetime.date(2025, 3, 16)
INFO:hotel_app.forms: - length_of_stay: 3
INFO:hotel_app.forms: - status_code: 'RE'
INFO:hotel_app.forms: - notes: ''
INFO:hotel_app.views:Created new reservation - ID: 1
INFO:hotel_app.views:Redirecting to confirmation page for reservation 1
INFO:hotel_app.views:Accessing reservation confirmation for reservation_id: 1
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
INFO:hotel_app.views:Found reservation for guest: Dr M. Taylor, Room: 301, Check-in: 2025-03-16
INFO:hotel_app.views:Rendering reservation confirmation page
INFO:hotel_app.models:Room __str__ called: 301
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
.INFO:hotel_app.views:Guest creation initiated in list mode by user: testuser
INFO:hotel_app.forms:Validating guest form data for James Wilson
INFO:hotel_app.models:Guest display_name property called: Mr J. Wilson
INFO:hotel_app.views:New guest created - ID: 1, Name: Mr J. Wilson
INFO:hotel_app.views:Redirecting to guest list after creating guest 1
INFO:hotel_app.views:Reservation creation initiated for guest_id: 1 by user: testuser
INFO:hotel_app.models:Guest display_name property called: Mr J. Wilson
INFO:hotel_app.views:Found guest for reservation: Mr J. Wilson
INFO:hotel_app.views:Retrieved room number from session: 201
INFO:hotel_app.views:Found room for reservation: Room 201 (Deluxe Room)
INFO:hotel_app.views:Reservation details:
INFO:hotel_app.models:Guest display_name property called: Mr J. Wilson
INFO:hotel_app.views: - Guest: Mr J. Wilson (ID: 1)
INFO:hotel_app.views: - Room: 201 (Deluxe Room)
INFO:hotel_app.views: - Check-in: 2025-03-02
INFO:hotel_app.views: - Length of stay: 3 nights
INFO:hotel_app.views: - Price per night: £200.00
INFO:hotel_app.views: - Total price: £600.00
INFO:hotel_app.views:Processing reservation form submission
INFO:hotel_app.models:Guest display_name property called: Mr J. Wilson
INFO:hotel_app.views:Reservation form validation successful
INFO:hotel_app.forms:Reservation Form save
INFO:hotel_app.forms: - reservation_id: None
INFO:hotel_app.forms: - guest: None
INFO:hotel_app.forms: - room_number: None
INFO:hotel_app.forms: - reservation_date_time: datetime.datetime(2025, 2, 23, 23, 57, 30, 75810, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
INFO:hotel_app.forms: - price: Decimal('600.00')
INFO:hotel_app.forms: - amount_paid: Decimal('600.00')
INFO:hotel_app.forms: - number_of_guests: 2
INFO:hotel_app.forms: - start_of_stay: datetime.date(2025, 3, 2)
INFO:hotel_app.forms: - length_of_stay: 3
INFO:hotel_app.forms: - status_code: 'RE'
INFO:hotel_app.forms: - notes: ''
INFO:hotel_app.views:Created new reservation - ID: 1
INFO:hotel_app.views:Redirecting to confirmation page for reservation 1
INFO:hotel_app.views:Accessing reservation confirmation for reservation_id: 1
INFO:hotel_app.models:Guest display_name property called: Mr J. Wilson
INFO:hotel_app.views:Found reservation for guest: Mr J. Wilson, Room: 201, Check-in: 2025-03-02
INFO:hotel_app.views:Rendering reservation confirmation page
INFO:hotel_app.models:Room __str__ called: 201
INFO:hotel_app.models:Guest display_name property called: Mr J. Wilson
INFO:hotel_app.views:Processing reservation update: <QueryDict: {'status_code': ['IN'], 'guest': ['1'], 'room_number': ['201'], 'reservation_date_time': ['2025-02-23 23:57:30.075810+00:00'], 'price': ['600.00'], 'amount_paid': ['600.00'], 'number_of_guests': ['2'], 'start_of_stay': ['2025-03-02'], 'length_of_stay': ['3']}>
INFO:hotel_app.models:Guest display_name property called: Mr J. Wilson
INFO:hotel_app.forms:Reservation Form save
INFO:hotel_app.forms: - reservation_id: 1
INFO:hotel_app.models:Guest __str__ called: ID:1: Full name:Mr James Wilson
INFO:hotel_app.forms: - guest: <Guest: ID:1: Full name:Mr James Wilson>
INFO:hotel_app.models:Room __str__ called: 201
INFO:hotel_app.forms: - room_number: <Room: 201>
INFO:hotel_app.forms: - reservation_date_time: datetime.datetime(2025, 2, 23, 23, 57, 30, 75810, tzinfo=datetime.timezone.utc)
INFO:hotel_app.forms: - price: Decimal('600.00')
INFO:hotel_app.forms: - amount_paid: Decimal('600.00')
INFO:hotel_app.forms: - number_of_guests: 2
INFO:hotel_app.forms: - start_of_stay: datetime.date(2025, 3, 2)
INFO:hotel_app.forms: - length_of_stay: 3
INFO:hotel_app.forms: - status_code: 'IN'
INFO:hotel_app.forms: - notes: ''
INFO:hotel_app.views:Reservation updated successfully
INFO:hotel_app.views:Reservation list view accessed by user: testuser
INFO:hotel_app.views:Filter parameters: <QueryDict: {}>
INFO:hotel_app.views:Reservation list view accessed by user: testuser
INFO:hotel_app.views:Filter parameters: <QueryDict: {}>
INFO:hotel_app.filters:Filtering reservations starting before 2025-02-23 but still occupying a room.
INFO:hotel_app.filters:Filtered available rooms count: 1
INFO:hotel_app.filters:Filtered reservations count: 1
INFO:hotel_app.models:Guest display_name property called: Mr J. Wilson
INFO:hotel_app.models:Room __str__ called: 201
INFO:hotel_app.views:Processing reservation update: <QueryDict: {'status_code': ['OT'], 'guest': ['1'], 'room_number': ['201'], 'reservation_date_time': ['2025-02-23 23:57:30.075810+00:00'], 'price': ['600.00'], 'amount_paid': ['600.00'], 'number_of_guests': ['2'], 'start_of_stay': ['2025-03-02'], 'length_of_stay': ['3']}>
INFO:hotel_app.models:Guest display_name property called: Mr J. Wilson
INFO:hotel_app.forms:Reservation Form save
INFO:hotel_app.forms: - reservation_id: 1
INFO:hotel_app.models:Guest __str__ called: ID:1: Full name:Mr James Wilson
INFO:hotel_app.forms: - guest: <Guest: ID:1: Full name:Mr James Wilson>
INFO:hotel_app.models:Room __str__ called: 201
INFO:hotel_app.forms: - room_number: <Room: 201>
INFO:hotel_app.forms: - reservation_date_time: datetime.datetime(2025, 2, 23, 23, 57, 30, 75810, tzinfo=datetime.timezone.utc)
INFO:hotel_app.forms: - price: Decimal('600.00')
INFO:hotel_app.forms: - amount_paid: Decimal('600.00')
INFO:hotel_app.forms: - number_of_guests: 2
INFO:hotel_app.forms: - start_of_stay: datetime.date(2025, 3, 2)
INFO:hotel_app.forms: - length_of_stay: 3
INFO:hotel_app.forms: - status_code: 'OT'
INFO:hotel_app.forms: - notes: ''
INFO:hotel_app.views:Reservation updated successfully
INFO:hotel_app.views:Reservation list view accessed by user: testuser
INFO:hotel_app.views:Filter parameters: <QueryDict: {}>
INFO:hotel_app.views:Reservation list view accessed by user: testuser
INFO:hotel_app.views:Filter parameters: <QueryDict: {}>
INFO:hotel_app.filters:Filtering reservations starting before 2025-02-23 but still occupying a room.
INFO:hotel_app.filters:Filtered available rooms count: 1
INFO:hotel_app.filters:Filtered reservations count: 1
INFO:hotel_app.models:Guest display_name property called: Mr J. Wilson
INFO:hotel_app.models:Room __str__ called: 201
.INFO:hotel_app.views:Reservation creation initiated for guest_id: 1 by user: testuser
INFO:hotel_app.models:Guest display_name property called: Ms S. Brown
INFO:hotel_app.views:Found guest for reservation: Ms S. Brown
INFO:hotel_app.views:Retrieved room number from session: 101
INFO:hotel_app.views:Found room for reservation: Room 101 (Standard Room)
INFO:hotel_app.views:Reservation details:
INFO:hotel_app.models:Guest display_name property called: Ms S. Brown
INFO:hotel_app.views: - Guest: Ms S. Brown (ID: 1)
INFO:hotel_app.views: - Room: 101 (Standard Room)
INFO:hotel_app.views: - Check-in: 2025-03-09
INFO:hotel_app.views: - Length of stay: 3 nights
INFO:hotel_app.views: - Price per night: £100.00
INFO:hotel_app.views: - Total price: £300.00
INFO:hotel_app.views:Processing reservation form submission
INFO:hotel_app.models:Guest display_name property called: Ms S. Brown
INFO:hotel_app.views:Reservation form validation successful
INFO:hotel_app.forms:Reservation Form save
INFO:hotel_app.forms: - reservation_id: None
INFO:hotel_app.forms: - guest: None
INFO:hotel_app.forms: - room_number: None
INFO:hotel_app.forms: - reservation_date_time: datetime.datetime(2025, 2, 23, 23, 57, 32, 442846, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
INFO:hotel_app.forms: - price: Decimal('300.00')
INFO:hotel_app.forms: - amount_paid: Decimal('300.00')
INFO:hotel_app.forms: - number_of_guests: 2
INFO:hotel_app.forms: - start_of_stay: datetime.date(2025, 3, 9)
INFO:hotel_app.forms: - length_of_stay: 3
INFO:hotel_app.forms: - status_code: 'RE'
INFO:hotel_app.forms: - notes: ''
INFO:hotel_app.views:Created new reservation - ID: 1
INFO:hotel_app.views:Redirecting to confirmation page for reservation 1
INFO:hotel_app.views:Accessing reservation confirmation for reservation_id: 1
INFO:hotel_app.models:Guest display_name property called: Ms S. Brown
INFO:hotel_app.views:Found reservation for guest: Ms S. Brown, Room: 101, Check-in: 2025-03-09
INFO:hotel_app.views:Rendering reservation confirmation page
INFO:hotel_app.models:Room __str__ called: 101
INFO:hotel_app.models:Guest display_name property called: Ms S. Brown
INFO:hotel_app.views:Reservation creation initiated for guest_id: 1 by user: testuser
INFO:hotel_app.models:Guest display_name property called: Ms S. Brown
INFO:hotel_app.views:Found guest for reservation: Ms S. Brown
INFO:hotel_app.views:Retrieved room number from session: 101
INFO:hotel_app.views:Found room for reservation: Room 101 (Standard Room)
INFO:hotel_app.views:Reservation details:
INFO:hotel_app.models:Guest display_name property called: Ms S. Brown
INFO:hotel_app.views: - Guest: Ms S. Brown (ID: 1)
INFO:hotel_app.views: - Room: 101 (Standard Room)
INFO:hotel_app.views: - Check-in: 2025-03-10
INFO:hotel_app.views: - Length of stay: 2 nights
INFO:hotel_app.views: - Price per night: £100.00
INFO:hotel_app.views: - Total price: £200.00
INFO:hotel_app.views:Processing reservation form submission
INFO:hotel_app.models:Guest display_name property called: Ms S. Brown
INFO:hotel_app.views:Reservation form validation successful
INFO:hotel_app.forms:Reservation Form save
INFO:hotel_app.forms: - reservation_id: None
INFO:hotel_app.forms: - guest: None
INFO:hotel_app.forms: - room_number: None
INFO:hotel_app.forms: - reservation_date_time: datetime.datetime(2025, 2, 23, 23, 57, 32, 490024, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
INFO:hotel_app.forms: - price: Decimal('200.00')
INFO:hotel_app.forms: - amount_paid: Decimal('200.00')
INFO:hotel_app.forms: - number_of_guests: 1
INFO:hotel_app.forms: - start_of_stay: datetime.date(2025, 3, 10)
INFO:hotel_app.forms: - length_of_stay: 2
INFO:hotel_app.forms: - status_code: 'RE'
INFO:hotel_app.forms: - notes: ''
ERROR:django.request:Internal Server Error: /reservation/create/1
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\views.py", line 517, in reservation_create_view
    reservation = form.save()
                  ^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\forms.py", line 329, in save
    instance.save()
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\models.py", line 354, in save
    self.full_clean()  # Call full_clean before saving to force validation
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\db\models\base.py", line 1651, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'__all__': ['This room is already booked for the entered dates.']}
.
----------------------------------------------------------------------
Ran 3 tests in 6.474s

OK
Destroying test database for alias 'default'...


FAILED (errors=1)
PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.test_integration
Found 3 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
EEE
======================================================================
ERROR: test_payment_validation (hotel_app.test_integration.PaymentIntegrationTestCase.test_payment_validation)
Test payment validation during reservation creation and updates
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\test_integration.py", line 291, in test_payment_validation
    response = self.client.post(reverse('add_reservation'), invalid_payment_data)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'add_reservation' not found. 'add_reservation' is not a valid view function or pattern name.

======================================================================
ERROR: test_complete_reservation_flow (hotel_app.test_integration.ReservationFlowTestCase.test_complete_reservation_flow)    
Test the entire reservation process from guest creation to checkout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\test_integration.py", line 72, in test_complete_reservation_flow
    response = self.client.post(reverse('add_guest'), guest_data)
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'add_guest' not found. 'add_guest' is not a valid view function or pattern name.

======================================================================
ERROR: test_overlapping_reservations (hotel_app.test_integration.RoomAvailabilityIntegrationTestCase.test_overlapping_reservations)
Test that overlapping reservations are properly handled
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\test_integration.py", line 199, in test_overlapping_reservations
    response = self.client.post(reverse('add_reservation'), first_reservation_data)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan_1k98io6\.virtualenvs\hotel_project2-YmGfoupx\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'add_reservation' not found. 'add_reservation' is not a valid view function or pattern name.

----------------------------------------------------------------------
Ran 3 tests in 4.838s

FAILED (errors=3)
Destroying test database for alias 'default'...
PS C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project> python manage.py test hotel_app.test_integration
Found 3 test(s).
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
INFO:hotel_app.views:Reservation creation initiated for guest_id: 1 by user: testuser
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
INFO:hotel_app.views:Found guest for reservation: Dr M. Taylor
INFO:hotel_app.views:Retrieved room number from session: 301
INFO:hotel_app.views:Found room for reservation: Room 301 (Luxury Suite)
INFO:hotel_app.views:Reservation details:
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
INFO:hotel_app.views: - Guest: Dr M. Taylor (ID: 1)
INFO:hotel_app.views: - Room: 301 (Luxury Suite)
INFO:hotel_app.views: - Check-in: 2025-03-16
INFO:hotel_app.views: - Length of stay: 3 nights
INFO:hotel_app.views: - Price per night: £300.00
INFO:hotel_app.views: - Total price: £900.00
INFO:hotel_app.views:Processing reservation form submission
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
WARNING:hotel_app.views:Reservation form validation failed
INFO:hotel_app.views:Form errors: <ul class="errorlist"><li>amount_paid<ul class="errorlist"><li>Payment amount cannot exceed the total price of 900.00</li></ul></li><li>__all__<ul class="errorlist nonfield"><li>Payment amount is required</li></ul></li></ul>
INFO:hotel_app.views:Reservation creation initiated for guest_id: 1 by user: testuser
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
INFO:hotel_app.views:Found guest for reservation: Dr M. Taylor
INFO:hotel_app.views:Retrieved room number from session: 301
INFO:hotel_app.views:Found room for reservation: Room 301 (Luxury Suite)
INFO:hotel_app.views:Reservation details:
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
INFO:hotel_app.views: - Guest: Dr M. Taylor (ID: 1)
INFO:hotel_app.views: - Room: 301 (Luxury Suite)
INFO:hotel_app.views: - Check-in: 2025-03-16
INFO:hotel_app.views: - Length of stay: 3 nights
INFO:hotel_app.views: - Price per night: £300.00
INFO:hotel_app.views: - Total price: £900.00
INFO:hotel_app.views:Processing reservation form submission
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
INFO:hotel_app.views:Reservation form validation successful
INFO:hotel_app.forms:Reservation Form save
INFO:hotel_app.forms: - reservation_id: None
INFO:hotel_app.forms: - guest: None
INFO:hotel_app.forms: - room_number: None
INFO:hotel_app.forms: - reservation_date_time: datetime.datetime(2025, 2, 23, 23, 30, 57, 206957, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
INFO:hotel_app.forms: - price: Decimal('900.00')
INFO:hotel_app.forms: - amount_paid: Decimal('450.00')
INFO:hotel_app.forms: - number_of_guests: 2
INFO:hotel_app.forms: - start_of_stay: datetime.date(2025, 3, 16)
INFO:hotel_app.forms: - length_of_stay: 3
INFO:hotel_app.forms: - status_code: 'RE'
INFO:hotel_app.forms: - notes: ''
INFO:hotel_app.views:Created new reservation - ID: 1
INFO:hotel_app.views:Redirecting to confirmation page for reservation 1
INFO:hotel_app.views:Accessing reservation confirmation for reservation_id: 1
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
INFO:hotel_app.views:Found reservation for guest: Dr M. Taylor, Room: 301, Check-in: 2025-03-16
INFO:hotel_app.views:Rendering reservation confirmation page
INFO:hotel_app.models:Room __str__ called: 301
INFO:hotel_app.models:Guest display_name property called: Dr M. Taylor
FINFO:hotel_app.views:Guest creation initiated in list mode by user: testuser
INFO:hotel_app.forms:Validating guest form data for James Wilson
INFO:hotel_app.models:Guest display_name property called: Mr J. Wilson
INFO:hotel_app.views:New guest created - ID: 1, Name: Mr J. Wilson
INFO:hotel_app.views:Redirecting to guest list after creating guest 1
FINFO:hotel_app.views:Reservation creation initiated for guest_id: 1 by user: testuser
INFO:hotel_app.models:Guest display_name property called: Ms S. Brown
INFO:hotel_app.views:Found guest for reservation: Ms S. Brown
INFO:hotel_app.views:Retrieved room number from session: 101
INFO:hotel_app.views:Found room for reservation: Room 101 (Standard Room)
INFO:hotel_app.views:Reservation details:
INFO:hotel_app.models:Guest display_name property called: Ms S. Brown
INFO:hotel_app.views: - Guest: Ms S. Brown (ID: 1)
INFO:hotel_app.views: - Room: 101 (Standard Room)
INFO:hotel_app.views: - Check-in: 2025-03-09
INFO:hotel_app.views: - Length of stay: 3 nights
INFO:hotel_app.views: - Price per night: £100.00
INFO:hotel_app.views: - Total price: £300.00
INFO:hotel_app.views:Processing reservation form submission
INFO:hotel_app.models:Guest display_name property called: Ms S. Brown
INFO:hotel_app.views:Reservation form validation successful
INFO:hotel_app.forms:Reservation Form save
INFO:hotel_app.forms: - reservation_id: None
INFO:hotel_app.forms: - guest: None
INFO:hotel_app.forms: - room_number: None
INFO:hotel_app.forms: - reservation_date_time: datetime.datetime(2025, 2, 23, 23, 31, 0, 414799, tzinfo=zoneinfo.ZoneInfo(key='UTC'))
INFO:hotel_app.forms: - price: Decimal('300.00')
INFO:hotel_app.forms: - amount_paid: Decimal('300.00')
INFO:hotel_app.forms: - number_of_guests: 2
INFO:hotel_app.forms: - start_of_stay: datetime.date(2025, 3, 9)
INFO:hotel_app.forms: - length_of_stay: 3
INFO:hotel_app.forms: - status_code: 'RE'
INFO:hotel_app.forms: - notes: ''
INFO:hotel_app.views:Created new reservation - ID: 1
INFO:hotel_app.views:Redirecting to confirmation page for reservation 1
INFO:hotel_app.views:Accessing reservation confirmation for reservation_id: 1
INFO:hotel_app.models:Guest display_name property called: Ms S. Brown
INFO:hotel_app.views:Found reservation for guest: Ms S. Brown, Room: 101, Check-in: 2025-03-09
INFO:hotel_app.views:Rendering reservation confirmation page
INFO:hotel_app.models:Room __str__ called: 101
INFO:hotel_app.models:Guest display_name property called: Ms S. Brown
F
======================================================================
FAIL: test_payment_validation (hotel_app.test_integration.PaymentIntegrationTestCase.test_payment_validation)
Test payment validation during reservation creation and updates
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\test_integration.py", line 368, in test_payment_validation
    self.assertEqual(response.status_code, 302)  # Should redirect after successful creation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 200 != 302

======================================================================
FAIL: test_complete_reservation_flow (hotel_app.test_integration.ReservationFlowTestCase.test_complete_reservation_flow)     
Test the entire reservation process from guest creation to checkout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\test_integration.py", line 73, in test_complete_reservation_flow
    self.assertEqual(response.status_code, 302)  # Should redirect after successful creation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 200 != 302

======================================================================
FAIL: test_overlapping_reservations (hotel_app.test_integration.RoomAvailabilityIntegrationTestCase.test_overlapping_reservations)
Test that overlapping reservations are properly handled
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\aidan_1k98io6\OneDrive\Documents\Assignment\Software Engineering\hotel_project2\hotel_project\hotel_app\test_integration.py", line 226, in test_overlapping_reservations
    self.assertEqual(response.status_code, 302)  # Should redirect after successful creation
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 200 != 302

----------------------------------------------------------------------
Ran 3 tests in 4.911s

FAILED (failures=3)
Destroying test database for alias 'default'...